export type {
  CreateDealDTO as CreateDealBody,
  DealDTO as Deal,
  DealDetailDTO as DealDetail,
  GetDealByIdDTO as GetDealById,
  GetDealsDTO as GetDeals,
  GetProgressDealDTO as GetProgressDeal,
  ProgressOptionDTO as ProgressOption,
  UpdateDealDTO as UpdateDeal,
} from "../api/types";
