export type {
  DealDTO as Deal,
  GetDealsDTO as GetDeals,
  UpdateDealDTO as UpdateDeal,
  GetDealByIdDTO as GetDealsById,
  ProgressOptionDTO as ProgressOption,
  GetProgressDealDTO as GetProgressDeal,
  CreateDealDTO as CreateDealBody,
} from "../api/types";
